services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
